# _config.yml

# Site settings
title: Abhishek Sharma
logo : DSC_0330-fotor-20230617132124.png
description: Software Engineer

# Theme settings
theme: jekyll-theme-minimal

# Plugins
plugins:
  - jekyll-feed

# Exclude files/folders from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site

# Build settings
markdown: kramdown
permalink: /:title/
