# _config.yml

# Site settings
title: Abhishek Sharma
logo : DSC_0330-fotor-20230617132124.png
description:
>
  <br>
  Software Engineer 3
  <br>
  <br>
  <a href="https://www.linkedin.com/in/abhishek-sharma-2209/">
    <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?&style=for-the-badge&logo=linkedin&logoColor=white">
  </a>
  <a href="mailto:abhishek2291995@gmail.com">
    <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" />
  </a>

# Theme settings
theme: jekyll-theme-minimal
